=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.4
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'cgi'

module EzmaxApi
  class ObjectPaymentpreparationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Download multiples attachments from an Paymentpreparation
    # @param pki_paymentpreparation_id [Integer] 
    # @param paymentpreparation_batch_download_v1_request [PaymentpreparationBatchDownloadV1Request] 
    # @param [Hash] opts the optional parameters
    # @return [File]
    def paymentpreparation_batch_download_v1(pki_paymentpreparation_id, paymentpreparation_batch_download_v1_request, opts = {})
      data, _status_code, _headers = paymentpreparation_batch_download_v1_with_http_info(pki_paymentpreparation_id, paymentpreparation_batch_download_v1_request, opts)
      data
    end

    # Download multiples attachments from an Paymentpreparation
    # @param pki_paymentpreparation_id [Integer] 
    # @param paymentpreparation_batch_download_v1_request [PaymentpreparationBatchDownloadV1Request] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(File, Integer, Hash)>] File data, response status code and response headers
    def paymentpreparation_batch_download_v1_with_http_info(pki_paymentpreparation_id, paymentpreparation_batch_download_v1_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectPaymentpreparationApi.paymentpreparation_batch_download_v1 ...'
      end
      # verify the required parameter 'pki_paymentpreparation_id' is set
      if @api_client.config.client_side_validation && pki_paymentpreparation_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_paymentpreparation_id' when calling ObjectPaymentpreparationApi.paymentpreparation_batch_download_v1"
      end
      if @api_client.config.client_side_validation && pki_paymentpreparation_id > 16777215
        fail ArgumentError, 'invalid value for "pki_paymentpreparation_id" when calling ObjectPaymentpreparationApi.paymentpreparation_batch_download_v1, must be smaller than or equal to 16777215.'
      end

      if @api_client.config.client_side_validation && pki_paymentpreparation_id < 0
        fail ArgumentError, 'invalid value for "pki_paymentpreparation_id" when calling ObjectPaymentpreparationApi.paymentpreparation_batch_download_v1, must be greater than or equal to 0.'
      end

      # verify the required parameter 'paymentpreparation_batch_download_v1_request' is set
      if @api_client.config.client_side_validation && paymentpreparation_batch_download_v1_request.nil?
        fail ArgumentError, "Missing the required parameter 'paymentpreparation_batch_download_v1_request' when calling ObjectPaymentpreparationApi.paymentpreparation_batch_download_v1"
      end
      # resource path
      local_var_path = '/1/object/paymentpreparation/{pkiPaymentpreparationID}/batchDownload'.sub('{pkiPaymentpreparationID}', CGI.escape(pki_paymentpreparation_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/zip', 'text/xml', 'application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(paymentpreparation_batch_download_v1_request)

      # return_type
      return_type = opts[:debug_return_type] || 'File'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectPaymentpreparationApi.paymentpreparation_batch_download_v1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectPaymentpreparationApi#paymentpreparation_batch_download_v1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve Paymentpreparation's attachments
    # @param pki_paymentpreparation_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [PaymentpreparationGetAttachmentsV1Response]
    def paymentpreparation_get_attachments_v1(pki_paymentpreparation_id, opts = {})
      data, _status_code, _headers = paymentpreparation_get_attachments_v1_with_http_info(pki_paymentpreparation_id, opts)
      data
    end

    # Retrieve Paymentpreparation&#39;s attachments
    # @param pki_paymentpreparation_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(PaymentpreparationGetAttachmentsV1Response, Integer, Hash)>] PaymentpreparationGetAttachmentsV1Response data, response status code and response headers
    def paymentpreparation_get_attachments_v1_with_http_info(pki_paymentpreparation_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectPaymentpreparationApi.paymentpreparation_get_attachments_v1 ...'
      end
      # verify the required parameter 'pki_paymentpreparation_id' is set
      if @api_client.config.client_side_validation && pki_paymentpreparation_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_paymentpreparation_id' when calling ObjectPaymentpreparationApi.paymentpreparation_get_attachments_v1"
      end
      if @api_client.config.client_side_validation && pki_paymentpreparation_id > 16777215
        fail ArgumentError, 'invalid value for "pki_paymentpreparation_id" when calling ObjectPaymentpreparationApi.paymentpreparation_get_attachments_v1, must be smaller than or equal to 16777215.'
      end

      if @api_client.config.client_side_validation && pki_paymentpreparation_id < 0
        fail ArgumentError, 'invalid value for "pki_paymentpreparation_id" when calling ObjectPaymentpreparationApi.paymentpreparation_get_attachments_v1, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = '/1/object/paymentpreparation/{pkiPaymentpreparationID}/getAttachments'.sub('{pkiPaymentpreparationID}', CGI.escape(pki_paymentpreparation_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PaymentpreparationGetAttachmentsV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectPaymentpreparationApi.paymentpreparation_get_attachments_v1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectPaymentpreparationApi#paymentpreparation_get_attachments_v1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Import attachments into the Paymentpreparation
    # @param pki_paymentpreparation_id [Integer] 
    # @param paymentpreparation_import_into_edmv1_request [PaymentpreparationImportIntoEDMV1Request] 
    # @param [Hash] opts the optional parameters
    # @return [PaymentpreparationImportIntoEDMV1Response]
    def paymentpreparation_import_into_edmv1(pki_paymentpreparation_id, paymentpreparation_import_into_edmv1_request, opts = {})
      data, _status_code, _headers = paymentpreparation_import_into_edmv1_with_http_info(pki_paymentpreparation_id, paymentpreparation_import_into_edmv1_request, opts)
      data
    end

    # Import attachments into the Paymentpreparation
    # @param pki_paymentpreparation_id [Integer] 
    # @param paymentpreparation_import_into_edmv1_request [PaymentpreparationImportIntoEDMV1Request] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(PaymentpreparationImportIntoEDMV1Response, Integer, Hash)>] PaymentpreparationImportIntoEDMV1Response data, response status code and response headers
    def paymentpreparation_import_into_edmv1_with_http_info(pki_paymentpreparation_id, paymentpreparation_import_into_edmv1_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectPaymentpreparationApi.paymentpreparation_import_into_edmv1 ...'
      end
      # verify the required parameter 'pki_paymentpreparation_id' is set
      if @api_client.config.client_side_validation && pki_paymentpreparation_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_paymentpreparation_id' when calling ObjectPaymentpreparationApi.paymentpreparation_import_into_edmv1"
      end
      if @api_client.config.client_side_validation && pki_paymentpreparation_id > 16777215
        fail ArgumentError, 'invalid value for "pki_paymentpreparation_id" when calling ObjectPaymentpreparationApi.paymentpreparation_import_into_edmv1, must be smaller than or equal to 16777215.'
      end

      if @api_client.config.client_side_validation && pki_paymentpreparation_id < 0
        fail ArgumentError, 'invalid value for "pki_paymentpreparation_id" when calling ObjectPaymentpreparationApi.paymentpreparation_import_into_edmv1, must be greater than or equal to 0.'
      end

      # verify the required parameter 'paymentpreparation_import_into_edmv1_request' is set
      if @api_client.config.client_side_validation && paymentpreparation_import_into_edmv1_request.nil?
        fail ArgumentError, "Missing the required parameter 'paymentpreparation_import_into_edmv1_request' when calling ObjectPaymentpreparationApi.paymentpreparation_import_into_edmv1"
      end
      # resource path
      local_var_path = '/1/object/paymentpreparation/{pkiPaymentpreparationID}/importIntoEDM'.sub('{pkiPaymentpreparationID}', CGI.escape(pki_paymentpreparation_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(paymentpreparation_import_into_edmv1_request)

      # return_type
      return_type = opts[:debug_return_type] || 'PaymentpreparationImportIntoEDMV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectPaymentpreparationApi.paymentpreparation_import_into_edmv1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectPaymentpreparationApi#paymentpreparation_import_into_edmv1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
