=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'cgi'

module EzmaxApi
  class ObjectTranqcontractApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Retrieve Communication count
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [TranqcontractGetCommunicationCountV1Response]
    def tranqcontract_get_communication_count_v1(pki_tranqcontract_id, opts = {})
      data, _status_code, _headers = tranqcontract_get_communication_count_v1_with_http_info(pki_tranqcontract_id, opts)
      data
    end

    # Retrieve Communication count
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(TranqcontractGetCommunicationCountV1Response, Integer, Hash)>] TranqcontractGetCommunicationCountV1Response data, response status code and response headers
    def tranqcontract_get_communication_count_v1_with_http_info(pki_tranqcontract_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectTranqcontractApi.tranqcontract_get_communication_count_v1 ...'
      end
      # verify the required parameter 'pki_tranqcontract_id' is set
      if @api_client.config.client_side_validation && pki_tranqcontract_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_tranqcontract_id' when calling ObjectTranqcontractApi.tranqcontract_get_communication_count_v1"
      end
      if @api_client.config.client_side_validation && pki_tranqcontract_id > 16777215
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communication_count_v1, must be smaller than or equal to 16777215.'
      end

      if @api_client.config.client_side_validation && pki_tranqcontract_id < 0
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communication_count_v1, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationCount'.sub('{' + 'pkiTranqcontractID' + '}', CGI.escape(pki_tranqcontract_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TranqcontractGetCommunicationCountV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectTranqcontractApi.tranqcontract_get_communication_count_v1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectTranqcontractApi#tranqcontract_get_communication_count_v1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve Communication list
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [TranqcontractGetCommunicationListV1Response]
    def tranqcontract_get_communication_list_v1(pki_tranqcontract_id, opts = {})
      data, _status_code, _headers = tranqcontract_get_communication_list_v1_with_http_info(pki_tranqcontract_id, opts)
      data
    end

    # Retrieve Communication list
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(TranqcontractGetCommunicationListV1Response, Integer, Hash)>] TranqcontractGetCommunicationListV1Response data, response status code and response headers
    def tranqcontract_get_communication_list_v1_with_http_info(pki_tranqcontract_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectTranqcontractApi.tranqcontract_get_communication_list_v1 ...'
      end
      # verify the required parameter 'pki_tranqcontract_id' is set
      if @api_client.config.client_side_validation && pki_tranqcontract_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_tranqcontract_id' when calling ObjectTranqcontractApi.tranqcontract_get_communication_list_v1"
      end
      if @api_client.config.client_side_validation && pki_tranqcontract_id > 16777215
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communication_list_v1, must be smaller than or equal to 16777215.'
      end

      if @api_client.config.client_side_validation && pki_tranqcontract_id < 0
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communication_list_v1, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationList'.sub('{' + 'pkiTranqcontractID' + '}', CGI.escape(pki_tranqcontract_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TranqcontractGetCommunicationListV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectTranqcontractApi.tranqcontract_get_communication_list_v1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectTranqcontractApi#tranqcontract_get_communication_list_v1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve Tranqcontract's Communicationrecipient
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [TranqcontractGetCommunicationrecipientsV1Response]
    def tranqcontract_get_communicationrecipients_v1(pki_tranqcontract_id, opts = {})
      data, _status_code, _headers = tranqcontract_get_communicationrecipients_v1_with_http_info(pki_tranqcontract_id, opts)
      data
    end

    # Retrieve Tranqcontract&#39;s Communicationrecipient
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(TranqcontractGetCommunicationrecipientsV1Response, Integer, Hash)>] TranqcontractGetCommunicationrecipientsV1Response data, response status code and response headers
    def tranqcontract_get_communicationrecipients_v1_with_http_info(pki_tranqcontract_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectTranqcontractApi.tranqcontract_get_communicationrecipients_v1 ...'
      end
      # verify the required parameter 'pki_tranqcontract_id' is set
      if @api_client.config.client_side_validation && pki_tranqcontract_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_tranqcontract_id' when calling ObjectTranqcontractApi.tranqcontract_get_communicationrecipients_v1"
      end
      if @api_client.config.client_side_validation && pki_tranqcontract_id > 16777215
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communicationrecipients_v1, must be smaller than or equal to 16777215.'
      end

      if @api_client.config.client_side_validation && pki_tranqcontract_id < 0
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communicationrecipients_v1, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationrecipients'.sub('{' + 'pkiTranqcontractID' + '}', CGI.escape(pki_tranqcontract_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TranqcontractGetCommunicationrecipientsV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectTranqcontractApi.tranqcontract_get_communicationrecipients_v1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectTranqcontractApi#tranqcontract_get_communicationrecipients_v1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve Tranqcontract's Communicationsender
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [TranqcontractGetCommunicationsendersV1Response]
    def tranqcontract_get_communicationsenders_v1(pki_tranqcontract_id, opts = {})
      data, _status_code, _headers = tranqcontract_get_communicationsenders_v1_with_http_info(pki_tranqcontract_id, opts)
      data
    end

    # Retrieve Tranqcontract&#39;s Communicationsender
    # 
    # @param pki_tranqcontract_id [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(TranqcontractGetCommunicationsendersV1Response, Integer, Hash)>] TranqcontractGetCommunicationsendersV1Response data, response status code and response headers
    def tranqcontract_get_communicationsenders_v1_with_http_info(pki_tranqcontract_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectTranqcontractApi.tranqcontract_get_communicationsenders_v1 ...'
      end
      # verify the required parameter 'pki_tranqcontract_id' is set
      if @api_client.config.client_side_validation && pki_tranqcontract_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_tranqcontract_id' when calling ObjectTranqcontractApi.tranqcontract_get_communicationsenders_v1"
      end
      if @api_client.config.client_side_validation && pki_tranqcontract_id > 16777215
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communicationsenders_v1, must be smaller than or equal to 16777215.'
      end

      if @api_client.config.client_side_validation && pki_tranqcontract_id < 0
        fail ArgumentError, 'invalid value for "pki_tranqcontract_id" when calling ObjectTranqcontractApi.tranqcontract_get_communicationsenders_v1, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationsenders'.sub('{' + 'pkiTranqcontractID' + '}', CGI.escape(pki_tranqcontract_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TranqcontractGetCommunicationsendersV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectTranqcontractApi.tranqcontract_get_communicationsenders_v1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectTranqcontractApi#tranqcontract_get_communicationsenders_v1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
