=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'cgi'

module EzmaxApi
  class ObjectBrokerApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Retrieve Brokers and IDs
    # Get the list of Broker to be used in a dropdown or autocomplete control.
    # @param s_selector [String] The type of Brokers to return
    # @param [Hash] opts the optional parameters
    # @option opts [String] :e_filter_active Specify which results we want to display. (default to 'Active')
    # @option opts [String] :s_query Allow to filter the returned results
    # @option opts [HeaderAcceptLanguage] :accept_language 
    # @return [BrokerGetAutocompleteV2Response]
    def broker_get_autocomplete_v2(s_selector, opts = {})
      data, _status_code, _headers = broker_get_autocomplete_v2_with_http_info(s_selector, opts)
      data
    end

    # Retrieve Brokers and IDs
    # Get the list of Broker to be used in a dropdown or autocomplete control.
    # @param s_selector [String] The type of Brokers to return
    # @param [Hash] opts the optional parameters
    # @option opts [String] :e_filter_active Specify which results we want to display. (default to 'Active')
    # @option opts [String] :s_query Allow to filter the returned results
    # @option opts [HeaderAcceptLanguage] :accept_language 
    # @return [Array<(BrokerGetAutocompleteV2Response, Integer, Hash)>] BrokerGetAutocompleteV2Response data, response status code and response headers
    def broker_get_autocomplete_v2_with_http_info(s_selector, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectBrokerApi.broker_get_autocomplete_v2 ...'
      end
      # verify the required parameter 's_selector' is set
      if @api_client.config.client_side_validation && s_selector.nil?
        fail ArgumentError, "Missing the required parameter 's_selector' when calling ObjectBrokerApi.broker_get_autocomplete_v2"
      end
      # verify enum value
      allowable_values = ["All"]
      if @api_client.config.client_side_validation && !allowable_values.include?(s_selector)
        fail ArgumentError, "invalid value for \"s_selector\", must be one of #{allowable_values}"
      end
      allowable_values = ["All", "Active", "Inactive"]
      if @api_client.config.client_side_validation && opts[:'e_filter_active'] && !allowable_values.include?(opts[:'e_filter_active'])
        fail ArgumentError, "invalid value for \"e_filter_active\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/2/object/broker/getAutocomplete/{sSelector}'.sub('{sSelector}', CGI.escape(s_selector.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'eFilterActive'] = opts[:'e_filter_active'] if !opts[:'e_filter_active'].nil?
      query_params[:'sQuery'] = opts[:'s_query'] if !opts[:'s_query'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'BrokerGetAutocompleteV2Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectBrokerApi.broker_get_autocomplete_v2",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectBrokerApi#broker_get_autocomplete_v2\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve Broker list
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :e_order_by Specify how you want the results to be sorted
    # @option opts [Integer] :i_row_max 
    # @option opts [Integer] :i_row_offset  (default to 0)
    # @option opts [HeaderAcceptLanguage] :accept_language 
    # @option opts [String] :s_filter 
    # @return [BrokerGetListV1Response]
    def broker_get_list_v1(opts = {})
      data, _status_code, _headers = broker_get_list_v1_with_http_info(opts)
      data
    end

    # Retrieve Broker list
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :e_order_by Specify how you want the results to be sorted
    # @option opts [Integer] :i_row_max 
    # @option opts [Integer] :i_row_offset  (default to 0)
    # @option opts [HeaderAcceptLanguage] :accept_language 
    # @option opts [String] :s_filter 
    # @return [Array<(BrokerGetListV1Response, Integer, Hash)>] BrokerGetListV1Response data, response status code and response headers
    def broker_get_list_v1_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectBrokerApi.broker_get_list_v1 ...'
      end
      allowable_values = ["pkiBrokerID_ASC", "pkiBrokerID_DESC", "fkiDepartmentID_ASC", "fkiDepartmentID_DESC", "sDepartmentNameX_ASC", "sDepartmentNameX_DESC", "sLanguageNameX_ASC", "sLanguageNameX_DESC", "fkiBrokertypeID_ASC", "fkiBrokertypeID_DESC", "sBrokertypeNameX_ASC", "sBrokertypeNameX_DESC", "sRealestateboardnumberNumber_ASC", "sRealestateboardnumberNumber_DESC", "sBrokerCode_ASC", "sBrokerCode_DESC", "iBrokerPhotocopiercode_ASC", "iBrokerPhotocopiercode_DESC", "iBrokerLongdistancecode_ASC", "iBrokerLongdistancecode_DESC", "sBrokerName_ASC", "sBrokerName_DESC", "iAgentBannernumber_ASC", "iAgentBannernumber_DESC", "sBrokerRealestateassociationlicense_ASC", "sBrokerRealestateassociationlicense_DESC", "dtBrokerHiredate_ASC", "dtBrokerHiredate_DESC", "dtBrokerLeavedate_ASC", "dtBrokerLeavedate_DESC", "bBrokerTranquillit_ASC", "bBrokerTranquillit_DESC", "bBrokerResidentiallicense_ASC", "bBrokerResidentiallicense_DESC", "bBrokerCommerciallicense_ASC", "bBrokerCommerciallicense_DESC", "bBrokerMortgagelicense_ASC", "bBrokerMortgagelicense_DESC", "bBrokerPaidbyofficetranquillit_ASC", "bBrokerPaidbyofficetranquillit_DESC", "dtBrokerFintraccertification_ASC", "dtBrokerFintraccertification_DESC", "sContactFirstname_ASC", "sContactFirstname_DESC", "sContactLastname_ASC", "sContactLastname_DESC", "dtContactBirthdate_ASC", "dtContactBirthdate_DESC", "sEmailAddress_ASC", "sEmailAddress_DESC", "sPhoneE164_ASC", "sPhoneE164_DESC", "sAddressCivic_ASC", "sAddressCivic_DESC", "sAddressStreet_ASC", "sAddressStreet_DESC", "sAddressSuite_ASC", "sAddressSuite_DESC", "sAddressCity_ASC", "sAddressCity_DESC", "sAddressZip_ASC", "sAddressZip_DESC", "sProvinceNameX_ASC", "sProvinceNameX_DESC", "sCountryNameX_ASC", "sCountryNameX_DESC", "bBrokerIsactive_ASC", "bBrokerIsactive_DESC"]
      if @api_client.config.client_side_validation && opts[:'e_order_by'] && !allowable_values.include?(opts[:'e_order_by'])
        fail ArgumentError, "invalid value for \"e_order_by\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'i_row_max'].nil? && opts[:'i_row_max'] > 10000
        fail ArgumentError, 'invalid value for "opts[:"i_row_max"]" when calling ObjectBrokerApi.broker_get_list_v1, must be smaller than or equal to 10000.'
      end

      if @api_client.config.client_side_validation && !opts[:'i_row_max'].nil? && opts[:'i_row_max'] < 1
        fail ArgumentError, 'invalid value for "opts[:"i_row_max"]" when calling ObjectBrokerApi.broker_get_list_v1, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'i_row_offset'].nil? && opts[:'i_row_offset'] < 0
        fail ArgumentError, 'invalid value for "opts[:"i_row_offset"]" when calling ObjectBrokerApi.broker_get_list_v1, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = '/1/object/broker/getList'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'eOrderBy'] = opts[:'e_order_by'] if !opts[:'e_order_by'].nil?
      query_params[:'iRowMax'] = opts[:'i_row_max'] if !opts[:'i_row_max'].nil?
      query_params[:'iRowOffset'] = opts[:'i_row_offset'] if !opts[:'i_row_offset'].nil?
      query_params[:'sFilter'] = opts[:'s_filter'] if !opts[:'s_filter'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']) unless header_params['Accept']
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'BrokerGetListV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectBrokerApi.broker_get_list_v1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectBrokerApi#broker_get_list_v1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Import attachments into the Broker
    # 
    # @param pki_broker_id [Integer] 
    # @param broker_import_into_edmv1_request [BrokerImportIntoEDMV1Request] 
    # @param [Hash] opts the optional parameters
    # @return [BrokerImportIntoEDMV1Response]
    def broker_import_into_edmv1(pki_broker_id, broker_import_into_edmv1_request, opts = {})
      data, _status_code, _headers = broker_import_into_edmv1_with_http_info(pki_broker_id, broker_import_into_edmv1_request, opts)
      data
    end

    # Import attachments into the Broker
    # 
    # @param pki_broker_id [Integer] 
    # @param broker_import_into_edmv1_request [BrokerImportIntoEDMV1Request] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(BrokerImportIntoEDMV1Response, Integer, Hash)>] BrokerImportIntoEDMV1Response data, response status code and response headers
    def broker_import_into_edmv1_with_http_info(pki_broker_id, broker_import_into_edmv1_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ObjectBrokerApi.broker_import_into_edmv1 ...'
      end
      # verify the required parameter 'pki_broker_id' is set
      if @api_client.config.client_side_validation && pki_broker_id.nil?
        fail ArgumentError, "Missing the required parameter 'pki_broker_id' when calling ObjectBrokerApi.broker_import_into_edmv1"
      end
      if @api_client.config.client_side_validation && pki_broker_id < 0
        fail ArgumentError, 'invalid value for "pki_broker_id" when calling ObjectBrokerApi.broker_import_into_edmv1, must be greater than or equal to 0.'
      end

      # verify the required parameter 'broker_import_into_edmv1_request' is set
      if @api_client.config.client_side_validation && broker_import_into_edmv1_request.nil?
        fail ArgumentError, "Missing the required parameter 'broker_import_into_edmv1_request' when calling ObjectBrokerApi.broker_import_into_edmv1"
      end
      # resource path
      local_var_path = '/1/object/broker/{pkiBrokerID}/importIntoEDM'.sub('{pkiBrokerID}', CGI.escape(pki_broker_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(broker_import_into_edmv1_request)

      # return_type
      return_type = opts[:debug_return_type] || 'BrokerImportIntoEDMV1Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Authorization']

      new_options = opts.merge(
        :operation => :"ObjectBrokerApi.broker_import_into_edmv1",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ObjectBrokerApi#broker_import_into_edmv1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
