=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for EzmaxApi::ObjectSupplyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ObjectSupplyApi' do
  before do
    # run before each test
    @api_instance = EzmaxApi::ObjectSupplyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ObjectSupplyApi' do
    it 'should create an instance of ObjectSupplyApi' do
      expect(@api_instance).to be_instance_of(EzmaxApi::ObjectSupplyApi)
    end
  end

  # unit tests for supply_create_object_v1
  # Create a new Supply
  # The endpoint allows to create one or many elements at once.
  # @param supply_create_object_v1_request 
  # @param [Hash] opts the optional parameters
  # @return [SupplyCreateObjectV1Response]
  describe 'supply_create_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for supply_delete_object_v1
  # Delete an existing Supply
  # 
  # @param pki_supply_id The unique ID of the Supply
  # @param [Hash] opts the optional parameters
  # @return [SupplyDeleteObjectV1Response]
  describe 'supply_delete_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for supply_edit_object_v1
  # Edit an existing Supply
  # 
  # @param pki_supply_id The unique ID of the Supply
  # @param supply_edit_object_v1_request 
  # @param [Hash] opts the optional parameters
  # @return [SupplyEditObjectV1Response]
  describe 'supply_edit_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for supply_get_autocomplete_v2
  # Retrieve Supplys and IDs
  # Get the list of Supply to be used in a dropdown or autocomplete control.
  # @param s_selector The type of Supplys to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :e_filter_active Specify which results we want to display.
  # @option opts [String] :s_query Allow to filter the returned results
  # @option opts [HeaderAcceptLanguage] :accept_language 
  # @return [SupplyGetAutocompleteV2Response]
  describe 'supply_get_autocomplete_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for supply_get_list_v1
  # Retrieve Supply list
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :e_order_by Specify how you want the results to be sorted
  # @option opts [Integer] :i_row_max 
  # @option opts [Integer] :i_row_offset 
  # @option opts [HeaderAcceptLanguage] :accept_language 
  # @option opts [String] :s_filter 
  # @return [SupplyGetListV1Response]
  describe 'supply_get_list_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for supply_get_object_v2
  # Retrieve an existing Supply
  # 
  # @param pki_supply_id The unique ID of the Supply
  # @param [Hash] opts the optional parameters
  # @return [SupplyGetObjectV2Response]
  describe 'supply_get_object_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
