=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for EzmaxApi::ObjectRejectedoffertopurchaseApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ObjectRejectedoffertopurchaseApi' do
  before do
    # run before each test
    @api_instance = EzmaxApi::ObjectRejectedoffertopurchaseApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ObjectRejectedoffertopurchaseApi' do
    it 'should create an instance of ObjectRejectedoffertopurchaseApi' do
      expect(@api_instance).to be_instance_of(EzmaxApi::ObjectRejectedoffertopurchaseApi)
    end
  end

  # unit tests for rejectedoffertopurchase_get_communication_list_v1
  # Retrieve Communication list
  # 
  # @param pki_rejectedoffertopurchase_id 
  # @param [Hash] opts the optional parameters
  # @return [RejectedoffertopurchaseGetCommunicationListV1Response]
  describe 'rejectedoffertopurchase_get_communication_list_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
