=begin
#eZmax API Definition

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.0.40
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for EzmaxApi::ObjectEzsignfolderApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ObjectEzsignfolderApi' do
  before do
    # run before each test
    @api_instance = EzmaxApi::ObjectEzsignfolderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ObjectEzsignfolderApi' do
    it 'should create an instance of ObjectEzsignfolderApi' do
      expect(@api_instance).to be_instance_of(EzmaxApi::ObjectEzsignfolderApi)
    end
  end

  # unit tests for ezsignfolder_create_object_v1
  # Create a new Ezsignfolder
  # The endpoint allows to create one or many elements at once.  The array can contain simple (Just the object) or compound (The object and its child) objects.  Creating compound elements allows to reduce the multiple requests to create all child objects.
  # @param ezsignfolder_create_object_v1_request 
  # @param [Hash] opts the optional parameters
  # @return [EzsignfolderCreateObjectV1Response]
  describe 'ezsignfolder_create_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ezsignfolder_delete_object_v1
  # Delete an existing Ezsignfolder
  # @param pki_ezsignfolder_id The unique ID of the Ezsignfolder
  # @param [Hash] opts the optional parameters
  # @return [EzsignfolderDeleteObjectV1Response]
  describe 'ezsignfolder_delete_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ezsignfolder_get_children_v1
  # Retrieve an existing Ezsignfolder&#39;s children IDs
  # @param pki_ezsignfolder_id The unique ID of the Ezsignfolder
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ezsignfolder_get_children_v1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ezsignfolder_get_object_v1
  # Retrieve an existing Ezsignfolder
  # @param pki_ezsignfolder_id The unique ID of the Ezsignfolder
  # @param [Hash] opts the optional parameters
  # @return [EzsignfolderGetObjectV1Response]
  describe 'ezsignfolder_get_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ezsignfolder_send_v1
  # Send the Ezsignfolder to the signatories for signature
  # @param pki_ezsignfolder_id The unique ID of the Ezsignfolder
  # @param ezsignfolder_send_v1_request 
  # @param [Hash] opts the optional parameters
  # @return [EzsignfolderSendV1Response]
  describe 'ezsignfolder_send_v1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
