=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for EzmaxApi::ObjectCorsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ObjectCorsApi' do
  before do
    # run before each test
    @api_instance = EzmaxApi::ObjectCorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ObjectCorsApi' do
    it 'should create an instance of ObjectCorsApi' do
      expect(@api_instance).to be_instance_of(EzmaxApi::ObjectCorsApi)
    end
  end

  # unit tests for cors_create_object_v1
  # Create a new Cors
  # The endpoint allows to create one or many elements at once.
  # @param cors_create_object_v1_request 
  # @param [Hash] opts the optional parameters
  # @return [CorsCreateObjectV1Response]
  describe 'cors_create_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cors_delete_object_v1
  # Delete an existing Cors
  # 
  # @param pki_cors_id The unique ID of the Cors
  # @param [Hash] opts the optional parameters
  # @return [CorsDeleteObjectV1Response]
  describe 'cors_delete_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cors_edit_object_v1
  # Edit an existing Cors
  # 
  # @param pki_cors_id The unique ID of the Cors
  # @param cors_edit_object_v1_request 
  # @param [Hash] opts the optional parameters
  # @return [CorsEditObjectV1Response]
  describe 'cors_edit_object_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cors_get_object_v2
  # Retrieve an existing Cors
  # 
  # @param pki_cors_id The unique ID of the Cors
  # @param [Hash] opts the optional parameters
  # @return [CorsGetObjectV2Response]
  describe 'cors_get_object_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
