=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::BillingentityinternalAutocompleteElementResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::BillingentityinternalAutocompleteElementResponse do
  let(:instance) { EzmaxApi::BillingentityinternalAutocompleteElementResponse.new }

  describe 'test an instance of BillingentityinternalAutocompleteElementResponse' do
    it 'should create an instance of BillingentityinternalAutocompleteElementResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(EzmaxApi::BillingentityinternalAutocompleteElementResponse)
    end
  end

  describe 'test attribute "pki_billingentityinternal_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "s_billingentityinternal_description_x"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "b_billingentityinternal_isactive"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
