=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::EzdoctemplatedocumentRequestPatch
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::EzdoctemplatedocumentRequestPatch do
  let(:instance) { EzmaxApi::EzdoctemplatedocumentRequestPatch.new }

  describe 'test an instance of EzdoctemplatedocumentRequestPatch' do
    it 'should create an instance of EzdoctemplatedocumentRequestPatch' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(EzmaxApi::EzdoctemplatedocumentRequestPatch)
    end
  end

  describe 'test attribute "e_ezdoctemplatedocument_format"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Docx", "Html", "Tx"])
      # validator.allowable_values.each do |value|
      #   expect { instance.e_ezdoctemplatedocument_format = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "s_ezdoctemplatedocument_fields"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "s_ezdoctemplatedocument_base64"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
