=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::EzsignfoldersignerassociationPatchObjectV1Request
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::EzsignfoldersignerassociationPatchObjectV1Request do
  let(:instance) { EzmaxApi::EzsignfoldersignerassociationPatchObjectV1Request.new }

  describe 'test an instance of EzsignfoldersignerassociationPatchObjectV1Request' do
    it 'should create an instance of EzsignfoldersignerassociationPatchObjectV1Request' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(EzmaxApi::EzsignfoldersignerassociationPatchObjectV1Request)
    end
  end

  describe 'test attribute "obj_ezsignfoldersignerassociation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
