=begin
#eZmax API Definition

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.0.39
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::EzsignsignatureCreateObjectV1Request
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::EzsignsignatureCreateObjectV1Request do
  let(:instance) { EzmaxApi::EzsignsignatureCreateObjectV1Request.new }

  describe 'test an instance of EzsignsignatureCreateObjectV1Request' do
    it 'should create an instance of EzsignsignatureCreateObjectV1Request' do
      expect(instance).to be_instance_of(EzmaxApi::EzsignsignatureCreateObjectV1Request)
    end
  end
  describe 'test attribute "obj_ezsignsignature"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "obj_ezsignsignature_compound"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
