=begin
#eZmax API Definition

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.0.41
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::EzsigndocumentDeleteObjectV1Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::EzsigndocumentDeleteObjectV1Response do
  let(:instance) { EzmaxApi::EzsigndocumentDeleteObjectV1Response.new }

  describe 'test an instance of EzsigndocumentDeleteObjectV1Response' do
    it 'should create an instance of EzsigndocumentDeleteObjectV1Response' do
      expect(instance).to be_instance_of(EzmaxApi::EzsigndocumentDeleteObjectV1Response)
    end
  end
  describe 'test attribute "obj_debug_payload"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "obj_debug"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
