=begin
#eZmax API Definition

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.4
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::EzsignformfieldgroupResponseCompoundAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::EzsignformfieldgroupResponseCompoundAllOf do
  let(:instance) { EzmaxApi::EzsignformfieldgroupResponseCompoundAllOf.new }

  describe 'test an instance of EzsignformfieldgroupResponseCompoundAllOf' do
    it 'should create an instance of EzsignformfieldgroupResponseCompoundAllOf' do
      expect(instance).to be_instance_of(EzmaxApi::EzsignformfieldgroupResponseCompoundAllOf)
    end
  end
  describe 'test attribute "a_obj_ezsignformfield"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
