=begin
#eZmax API Definition

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.4
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::EzsignsignatureEditObjectV1Request
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::EzsignsignatureEditObjectV1Request do
  let(:instance) { EzmaxApi::EzsignsignatureEditObjectV1Request.new }

  describe 'test an instance of EzsignsignatureEditObjectV1Request' do
    it 'should create an instance of EzsignsignatureEditObjectV1Request' do
      expect(instance).to be_instance_of(EzmaxApi::EzsignsignatureEditObjectV1Request)
    end
  end
  describe 'test attribute "obj_ezsignsignature"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
