=begin
#eZmax API Definition

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.0.48
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::EzsigndocumentGetDownloadUrlV1ResponseMPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::EzsigndocumentGetDownloadUrlV1ResponseMPayload do
  let(:instance) { EzmaxApi::EzsigndocumentGetDownloadUrlV1ResponseMPayload.new }

  describe 'test an instance of EzsigndocumentGetDownloadUrlV1ResponseMPayload' do
    it 'should create an instance of EzsigndocumentGetDownloadUrlV1ResponseMPayload' do
      expect(instance).to be_instance_of(EzmaxApi::EzsigndocumentGetDownloadUrlV1ResponseMPayload)
    end
  end
  describe 'test attribute "s_download_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
