=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::FieldEEzsignfoldertypePdfanoncompliantaction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::FieldEEzsignfoldertypePdfanoncompliantaction do
  let(:instance) { EzmaxApi::FieldEEzsignfoldertypePdfanoncompliantaction.new }

  describe 'test an instance of FieldEEzsignfoldertypePdfanoncompliantaction' do
    it 'should create an instance of FieldEEzsignfoldertypePdfanoncompliantaction' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(EzmaxApi::FieldEEzsignfoldertypePdfanoncompliantaction)
    end
  end

end
