=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::UserstagedGetObjectV2ResponseMPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::UserstagedGetObjectV2ResponseMPayload do
  let(:instance) { EzmaxApi::UserstagedGetObjectV2ResponseMPayload.new }

  describe 'test an instance of UserstagedGetObjectV2ResponseMPayload' do
    it 'should create an instance of UserstagedGetObjectV2ResponseMPayload' do
      expect(instance).to be_instance_of(EzmaxApi::UserstagedGetObjectV2ResponseMPayload)
    end
  end
  describe 'test attribute "obj_userstaged"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
