=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EzmaxApi::WebhookUserUserCreated
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe EzmaxApi::WebhookUserUserCreated do
  let(:instance) { EzmaxApi::WebhookUserUserCreated.new }

  describe 'test an instance of WebhookUserUserCreated' do
    it 'should create an instance of WebhookUserUserCreated' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(EzmaxApi::WebhookUserUserCreated)
    end
  end

  describe 'test attribute "obj_webhook"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "a_obj_attempt"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "obj_user"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
