=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module EzmaxApi
  # A Buyercontract List Element
  class BuyercontractListElement < ApiModelBase
    # The unique ID of the Buyercontract
    attr_accessor :pki_buyercontract_id

    # The unique ID of the Inscriptiontype
    attr_accessor :fki_inscriptiontype_id

    # The name of the Inscriptiontype in the language of the requester
    attr_accessor :s_inscriptiontype_name_x

    attr_accessor :e_buyercontract_step

    # The minimumprice of the Buyercontract
    attr_accessor :d_buyercontract_minimumprice

    # The maximumprice of the Buyercontract
    attr_accessor :d_buyercontract_maximumprice

    attr_accessor :e_buyercontract_type

    # The number of the Buyercontract
    attr_accessor :s_buyercontract_contract

    # The date of the Buyercontract
    attr_accessor :dt_buyercontract_date

    # The expirationdate of the Buyercontract
    attr_accessor :dt_buyercontract_expirationdate

    # Whether the buyercontract is active or not
    attr_accessor :b_buyercontract_isactive

    # The brokers' name of the Buyercontract
    attr_accessor :s_buyercontract_brokers

    # The buyers' name of the Buyercontract
    attr_accessor :s_buyercontract_buyers

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pki_buyercontract_id' => :'pkiBuyercontractID',
        :'fki_inscriptiontype_id' => :'fkiInscriptiontypeID',
        :'s_inscriptiontype_name_x' => :'sInscriptiontypeNameX',
        :'e_buyercontract_step' => :'eBuyercontractStep',
        :'d_buyercontract_minimumprice' => :'dBuyercontractMinimumprice',
        :'d_buyercontract_maximumprice' => :'dBuyercontractMaximumprice',
        :'e_buyercontract_type' => :'eBuyercontractType',
        :'s_buyercontract_contract' => :'sBuyercontractContract',
        :'dt_buyercontract_date' => :'dtBuyercontractDate',
        :'dt_buyercontract_expirationdate' => :'dtBuyercontractExpirationdate',
        :'b_buyercontract_isactive' => :'bBuyercontractIsactive',
        :'s_buyercontract_brokers' => :'sBuyercontractBrokers',
        :'s_buyercontract_buyers' => :'sBuyercontractBuyers'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pki_buyercontract_id' => :'Integer',
        :'fki_inscriptiontype_id' => :'Integer',
        :'s_inscriptiontype_name_x' => :'String',
        :'e_buyercontract_step' => :'FieldEBuyercontractStep',
        :'d_buyercontract_minimumprice' => :'String',
        :'d_buyercontract_maximumprice' => :'String',
        :'e_buyercontract_type' => :'FieldEBuyercontractType',
        :'s_buyercontract_contract' => :'String',
        :'dt_buyercontract_date' => :'String',
        :'dt_buyercontract_expirationdate' => :'String',
        :'b_buyercontract_isactive' => :'Boolean',
        :'s_buyercontract_brokers' => :'String',
        :'s_buyercontract_buyers' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `EzmaxApi::BuyercontractListElement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `EzmaxApi::BuyercontractListElement`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pki_buyercontract_id')
        self.pki_buyercontract_id = attributes[:'pki_buyercontract_id']
      else
        self.pki_buyercontract_id = nil
      end

      if attributes.key?(:'fki_inscriptiontype_id')
        self.fki_inscriptiontype_id = attributes[:'fki_inscriptiontype_id']
      else
        self.fki_inscriptiontype_id = nil
      end

      if attributes.key?(:'s_inscriptiontype_name_x')
        self.s_inscriptiontype_name_x = attributes[:'s_inscriptiontype_name_x']
      else
        self.s_inscriptiontype_name_x = nil
      end

      if attributes.key?(:'e_buyercontract_step')
        self.e_buyercontract_step = attributes[:'e_buyercontract_step']
      else
        self.e_buyercontract_step = nil
      end

      if attributes.key?(:'d_buyercontract_minimumprice')
        self.d_buyercontract_minimumprice = attributes[:'d_buyercontract_minimumprice']
      else
        self.d_buyercontract_minimumprice = nil
      end

      if attributes.key?(:'d_buyercontract_maximumprice')
        self.d_buyercontract_maximumprice = attributes[:'d_buyercontract_maximumprice']
      else
        self.d_buyercontract_maximumprice = nil
      end

      if attributes.key?(:'e_buyercontract_type')
        self.e_buyercontract_type = attributes[:'e_buyercontract_type']
      else
        self.e_buyercontract_type = nil
      end

      if attributes.key?(:'s_buyercontract_contract')
        self.s_buyercontract_contract = attributes[:'s_buyercontract_contract']
      end

      if attributes.key?(:'dt_buyercontract_date')
        self.dt_buyercontract_date = attributes[:'dt_buyercontract_date']
      else
        self.dt_buyercontract_date = nil
      end

      if attributes.key?(:'dt_buyercontract_expirationdate')
        self.dt_buyercontract_expirationdate = attributes[:'dt_buyercontract_expirationdate']
      end

      if attributes.key?(:'b_buyercontract_isactive')
        self.b_buyercontract_isactive = attributes[:'b_buyercontract_isactive']
      else
        self.b_buyercontract_isactive = nil
      end

      if attributes.key?(:'s_buyercontract_brokers')
        self.s_buyercontract_brokers = attributes[:'s_buyercontract_brokers']
      else
        self.s_buyercontract_brokers = nil
      end

      if attributes.key?(:'s_buyercontract_buyers')
        self.s_buyercontract_buyers = attributes[:'s_buyercontract_buyers']
      else
        self.s_buyercontract_buyers = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @pki_buyercontract_id.nil?
        invalid_properties.push('invalid value for "pki_buyercontract_id", pki_buyercontract_id cannot be nil.')
      end

      if @pki_buyercontract_id > 65535
        invalid_properties.push('invalid value for "pki_buyercontract_id", must be smaller than or equal to 65535.')
      end

      if @pki_buyercontract_id < 1
        invalid_properties.push('invalid value for "pki_buyercontract_id", must be greater than or equal to 1.')
      end

      if @fki_inscriptiontype_id.nil?
        invalid_properties.push('invalid value for "fki_inscriptiontype_id", fki_inscriptiontype_id cannot be nil.')
      end

      if @fki_inscriptiontype_id > 255
        invalid_properties.push('invalid value for "fki_inscriptiontype_id", must be smaller than or equal to 255.')
      end

      if @fki_inscriptiontype_id < 0
        invalid_properties.push('invalid value for "fki_inscriptiontype_id", must be greater than or equal to 0.')
      end

      if @s_inscriptiontype_name_x.nil?
        invalid_properties.push('invalid value for "s_inscriptiontype_name_x", s_inscriptiontype_name_x cannot be nil.')
      end

      pattern = Regexp.new(/^.{0,30}$/)
      if @s_inscriptiontype_name_x !~ pattern
        invalid_properties.push("invalid value for \"s_inscriptiontype_name_x\", must conform to the pattern #{pattern}.")
      end

      if @e_buyercontract_step.nil?
        invalid_properties.push('invalid value for "e_buyercontract_step", e_buyercontract_step cannot be nil.')
      end

      if @d_buyercontract_minimumprice.nil?
        invalid_properties.push('invalid value for "d_buyercontract_minimumprice", d_buyercontract_minimumprice cannot be nil.')
      end

      if @d_buyercontract_minimumprice.to_s.length > 13
        invalid_properties.push('invalid value for "d_buyercontract_minimumprice", the character length must be smaller than or equal to 13.')
      end

      if @d_buyercontract_minimumprice.to_s.length < 4
        invalid_properties.push('invalid value for "d_buyercontract_minimumprice", the character length must be greater than or equal to 4.')
      end

      pattern = Regexp.new(/^-{0,1}[\d]{1,9}?\.[\d]{2}$/)
      if @d_buyercontract_minimumprice !~ pattern
        invalid_properties.push("invalid value for \"d_buyercontract_minimumprice\", must conform to the pattern #{pattern}.")
      end

      if @d_buyercontract_maximumprice.nil?
        invalid_properties.push('invalid value for "d_buyercontract_maximumprice", d_buyercontract_maximumprice cannot be nil.')
      end

      if @d_buyercontract_maximumprice.to_s.length > 13
        invalid_properties.push('invalid value for "d_buyercontract_maximumprice", the character length must be smaller than or equal to 13.')
      end

      if @d_buyercontract_maximumprice.to_s.length < 4
        invalid_properties.push('invalid value for "d_buyercontract_maximumprice", the character length must be greater than or equal to 4.')
      end

      pattern = Regexp.new(/^-{0,1}[\d]{1,9}?\.[\d]{2}$/)
      if @d_buyercontract_maximumprice !~ pattern
        invalid_properties.push("invalid value for \"d_buyercontract_maximumprice\", must conform to the pattern #{pattern}.")
      end

      if @e_buyercontract_type.nil?
        invalid_properties.push('invalid value for "e_buyercontract_type", e_buyercontract_type cannot be nil.')
      end

      if @dt_buyercontract_date.nil?
        invalid_properties.push('invalid value for "dt_buyercontract_date", dt_buyercontract_date cannot be nil.')
      end

      pattern = Regexp.new(/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/)
      if @dt_buyercontract_date !~ pattern
        invalid_properties.push("invalid value for \"dt_buyercontract_date\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/)
      if !@dt_buyercontract_expirationdate.nil? && @dt_buyercontract_expirationdate !~ pattern
        invalid_properties.push("invalid value for \"dt_buyercontract_expirationdate\", must conform to the pattern #{pattern}.")
      end

      if @b_buyercontract_isactive.nil?
        invalid_properties.push('invalid value for "b_buyercontract_isactive", b_buyercontract_isactive cannot be nil.')
      end

      if @s_buyercontract_brokers.nil?
        invalid_properties.push('invalid value for "s_buyercontract_brokers", s_buyercontract_brokers cannot be nil.')
      end

      if @s_buyercontract_buyers.nil?
        invalid_properties.push('invalid value for "s_buyercontract_buyers", s_buyercontract_buyers cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @pki_buyercontract_id.nil?
      return false if @pki_buyercontract_id > 65535
      return false if @pki_buyercontract_id < 1
      return false if @fki_inscriptiontype_id.nil?
      return false if @fki_inscriptiontype_id > 255
      return false if @fki_inscriptiontype_id < 0
      return false if @s_inscriptiontype_name_x.nil?
      return false if @s_inscriptiontype_name_x !~ Regexp.new(/^.{0,30}$/)
      return false if @e_buyercontract_step.nil?
      return false if @d_buyercontract_minimumprice.nil?
      return false if @d_buyercontract_minimumprice.to_s.length > 13
      return false if @d_buyercontract_minimumprice.to_s.length < 4
      return false if @d_buyercontract_minimumprice !~ Regexp.new(/^-{0,1}[\d]{1,9}?\.[\d]{2}$/)
      return false if @d_buyercontract_maximumprice.nil?
      return false if @d_buyercontract_maximumprice.to_s.length > 13
      return false if @d_buyercontract_maximumprice.to_s.length < 4
      return false if @d_buyercontract_maximumprice !~ Regexp.new(/^-{0,1}[\d]{1,9}?\.[\d]{2}$/)
      return false if @e_buyercontract_type.nil?
      return false if @dt_buyercontract_date.nil?
      return false if @dt_buyercontract_date !~ Regexp.new(/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/)
      return false if !@dt_buyercontract_expirationdate.nil? && @dt_buyercontract_expirationdate !~ Regexp.new(/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/)
      return false if @b_buyercontract_isactive.nil?
      return false if @s_buyercontract_brokers.nil?
      return false if @s_buyercontract_buyers.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] pki_buyercontract_id Value to be assigned
    def pki_buyercontract_id=(pki_buyercontract_id)
      if pki_buyercontract_id.nil?
        fail ArgumentError, 'pki_buyercontract_id cannot be nil'
      end

      if pki_buyercontract_id > 65535
        fail ArgumentError, 'invalid value for "pki_buyercontract_id", must be smaller than or equal to 65535.'
      end

      if pki_buyercontract_id < 1
        fail ArgumentError, 'invalid value for "pki_buyercontract_id", must be greater than or equal to 1.'
      end

      @pki_buyercontract_id = pki_buyercontract_id
    end

    # Custom attribute writer method with validation
    # @param [Object] fki_inscriptiontype_id Value to be assigned
    def fki_inscriptiontype_id=(fki_inscriptiontype_id)
      if fki_inscriptiontype_id.nil?
        fail ArgumentError, 'fki_inscriptiontype_id cannot be nil'
      end

      if fki_inscriptiontype_id > 255
        fail ArgumentError, 'invalid value for "fki_inscriptiontype_id", must be smaller than or equal to 255.'
      end

      if fki_inscriptiontype_id < 0
        fail ArgumentError, 'invalid value for "fki_inscriptiontype_id", must be greater than or equal to 0.'
      end

      @fki_inscriptiontype_id = fki_inscriptiontype_id
    end

    # Custom attribute writer method with validation
    # @param [Object] s_inscriptiontype_name_x Value to be assigned
    def s_inscriptiontype_name_x=(s_inscriptiontype_name_x)
      if s_inscriptiontype_name_x.nil?
        fail ArgumentError, 's_inscriptiontype_name_x cannot be nil'
      end

      pattern = Regexp.new(/^.{0,30}$/)
      if s_inscriptiontype_name_x !~ pattern
        fail ArgumentError, "invalid value for \"s_inscriptiontype_name_x\", must conform to the pattern #{pattern}."
      end

      @s_inscriptiontype_name_x = s_inscriptiontype_name_x
    end

    # Custom attribute writer method with validation
    # @param [Object] e_buyercontract_step Value to be assigned
    def e_buyercontract_step=(e_buyercontract_step)
      if e_buyercontract_step.nil?
        fail ArgumentError, 'e_buyercontract_step cannot be nil'
      end

      @e_buyercontract_step = e_buyercontract_step
    end

    # Custom attribute writer method with validation
    # @param [Object] d_buyercontract_minimumprice Value to be assigned
    def d_buyercontract_minimumprice=(d_buyercontract_minimumprice)
      if d_buyercontract_minimumprice.nil?
        fail ArgumentError, 'd_buyercontract_minimumprice cannot be nil'
      end

      if d_buyercontract_minimumprice.to_s.length > 13
        fail ArgumentError, 'invalid value for "d_buyercontract_minimumprice", the character length must be smaller than or equal to 13.'
      end

      if d_buyercontract_minimumprice.to_s.length < 4
        fail ArgumentError, 'invalid value for "d_buyercontract_minimumprice", the character length must be greater than or equal to 4.'
      end

      pattern = Regexp.new(/^-{0,1}[\d]{1,9}?\.[\d]{2}$/)
      if d_buyercontract_minimumprice !~ pattern
        fail ArgumentError, "invalid value for \"d_buyercontract_minimumprice\", must conform to the pattern #{pattern}."
      end

      @d_buyercontract_minimumprice = d_buyercontract_minimumprice
    end

    # Custom attribute writer method with validation
    # @param [Object] d_buyercontract_maximumprice Value to be assigned
    def d_buyercontract_maximumprice=(d_buyercontract_maximumprice)
      if d_buyercontract_maximumprice.nil?
        fail ArgumentError, 'd_buyercontract_maximumprice cannot be nil'
      end

      if d_buyercontract_maximumprice.to_s.length > 13
        fail ArgumentError, 'invalid value for "d_buyercontract_maximumprice", the character length must be smaller than or equal to 13.'
      end

      if d_buyercontract_maximumprice.to_s.length < 4
        fail ArgumentError, 'invalid value for "d_buyercontract_maximumprice", the character length must be greater than or equal to 4.'
      end

      pattern = Regexp.new(/^-{0,1}[\d]{1,9}?\.[\d]{2}$/)
      if d_buyercontract_maximumprice !~ pattern
        fail ArgumentError, "invalid value for \"d_buyercontract_maximumprice\", must conform to the pattern #{pattern}."
      end

      @d_buyercontract_maximumprice = d_buyercontract_maximumprice
    end

    # Custom attribute writer method with validation
    # @param [Object] e_buyercontract_type Value to be assigned
    def e_buyercontract_type=(e_buyercontract_type)
      if e_buyercontract_type.nil?
        fail ArgumentError, 'e_buyercontract_type cannot be nil'
      end

      @e_buyercontract_type = e_buyercontract_type
    end

    # Custom attribute writer method with validation
    # @param [Object] dt_buyercontract_date Value to be assigned
    def dt_buyercontract_date=(dt_buyercontract_date)
      if dt_buyercontract_date.nil?
        fail ArgumentError, 'dt_buyercontract_date cannot be nil'
      end

      pattern = Regexp.new(/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/)
      if dt_buyercontract_date !~ pattern
        fail ArgumentError, "invalid value for \"dt_buyercontract_date\", must conform to the pattern #{pattern}."
      end

      @dt_buyercontract_date = dt_buyercontract_date
    end

    # Custom attribute writer method with validation
    # @param [Object] dt_buyercontract_expirationdate Value to be assigned
    def dt_buyercontract_expirationdate=(dt_buyercontract_expirationdate)
      if dt_buyercontract_expirationdate.nil?
        fail ArgumentError, 'dt_buyercontract_expirationdate cannot be nil'
      end

      pattern = Regexp.new(/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/)
      if dt_buyercontract_expirationdate !~ pattern
        fail ArgumentError, "invalid value for \"dt_buyercontract_expirationdate\", must conform to the pattern #{pattern}."
      end

      @dt_buyercontract_expirationdate = dt_buyercontract_expirationdate
    end

    # Custom attribute writer method with validation
    # @param [Object] b_buyercontract_isactive Value to be assigned
    def b_buyercontract_isactive=(b_buyercontract_isactive)
      if b_buyercontract_isactive.nil?
        fail ArgumentError, 'b_buyercontract_isactive cannot be nil'
      end

      @b_buyercontract_isactive = b_buyercontract_isactive
    end

    # Custom attribute writer method with validation
    # @param [Object] s_buyercontract_brokers Value to be assigned
    def s_buyercontract_brokers=(s_buyercontract_brokers)
      if s_buyercontract_brokers.nil?
        fail ArgumentError, 's_buyercontract_brokers cannot be nil'
      end

      @s_buyercontract_brokers = s_buyercontract_brokers
    end

    # Custom attribute writer method with validation
    # @param [Object] s_buyercontract_buyers Value to be assigned
    def s_buyercontract_buyers=(s_buyercontract_buyers)
      if s_buyercontract_buyers.nil?
        fail ArgumentError, 's_buyercontract_buyers cannot be nil'
      end

      @s_buyercontract_buyers = s_buyercontract_buyers
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pki_buyercontract_id == o.pki_buyercontract_id &&
          fki_inscriptiontype_id == o.fki_inscriptiontype_id &&
          s_inscriptiontype_name_x == o.s_inscriptiontype_name_x &&
          e_buyercontract_step == o.e_buyercontract_step &&
          d_buyercontract_minimumprice == o.d_buyercontract_minimumprice &&
          d_buyercontract_maximumprice == o.d_buyercontract_maximumprice &&
          e_buyercontract_type == o.e_buyercontract_type &&
          s_buyercontract_contract == o.s_buyercontract_contract &&
          dt_buyercontract_date == o.dt_buyercontract_date &&
          dt_buyercontract_expirationdate == o.dt_buyercontract_expirationdate &&
          b_buyercontract_isactive == o.b_buyercontract_isactive &&
          s_buyercontract_brokers == o.s_buyercontract_brokers &&
          s_buyercontract_buyers == o.s_buyercontract_buyers
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pki_buyercontract_id, fki_inscriptiontype_id, s_inscriptiontype_name_x, e_buyercontract_step, d_buyercontract_minimumprice, d_buyercontract_maximumprice, e_buyercontract_type, s_buyercontract_contract, dt_buyercontract_date, dt_buyercontract_expirationdate, b_buyercontract_isactive, s_buyercontract_brokers, s_buyercontract_buyers].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
