=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module EzmaxApi
  # An Ezsignbulksend List Element
  class EzsignbulksendListElement
    # The unique ID of the Ezsignbulksend
    attr_accessor :pki_ezsignbulksend_id

    # The unique ID of the Ezsignfoldertype.
    attr_accessor :fki_ezsignfoldertype_id

    # The description of the Ezsignbulksend
    attr_accessor :s_ezsignbulksend_description

    # The name of the Ezsignfoldertype in the language of the requester
    attr_accessor :s_ezsignfoldertype_name_x

    # Whether the Ezsigntemplatepackage was automatically modified and needs a manual validation
    attr_accessor :b_ezsignbulksend_needvalidation

    # The total number of Ezsignbulksendtransmissions in the Ezsignbulksend
    attr_accessor :i_ezsignbulksendtransmission

    # The total number of Ezsignfolders in the Ezsignbulksend
    attr_accessor :i_ezsignfolder

    # The total number of Ezsigndocuments in the Ezsignbulksend
    attr_accessor :i_ezsigndocument

    # The total number of Ezsignsignature in the Ezsignbulksend
    attr_accessor :i_ezsignsignature

    # The total number of already signed Ezsignsignature blocks in the Ezsignbulksend
    attr_accessor :i_ezsignsignature_signed

    # Whether the Ezsignbulksend is active or not
    attr_accessor :b_ezsignbulksend_isactive

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pki_ezsignbulksend_id' => :'pkiEzsignbulksendID',
        :'fki_ezsignfoldertype_id' => :'fkiEzsignfoldertypeID',
        :'s_ezsignbulksend_description' => :'sEzsignbulksendDescription',
        :'s_ezsignfoldertype_name_x' => :'sEzsignfoldertypeNameX',
        :'b_ezsignbulksend_needvalidation' => :'bEzsignbulksendNeedvalidation',
        :'i_ezsignbulksendtransmission' => :'iEzsignbulksendtransmission',
        :'i_ezsignfolder' => :'iEzsignfolder',
        :'i_ezsigndocument' => :'iEzsigndocument',
        :'i_ezsignsignature' => :'iEzsignsignature',
        :'i_ezsignsignature_signed' => :'iEzsignsignatureSigned',
        :'b_ezsignbulksend_isactive' => :'bEzsignbulksendIsactive'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pki_ezsignbulksend_id' => :'Integer',
        :'fki_ezsignfoldertype_id' => :'Integer',
        :'s_ezsignbulksend_description' => :'String',
        :'s_ezsignfoldertype_name_x' => :'String',
        :'b_ezsignbulksend_needvalidation' => :'Boolean',
        :'i_ezsignbulksendtransmission' => :'Integer',
        :'i_ezsignfolder' => :'Integer',
        :'i_ezsigndocument' => :'Integer',
        :'i_ezsignsignature' => :'Integer',
        :'i_ezsignsignature_signed' => :'Integer',
        :'b_ezsignbulksend_isactive' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `EzmaxApi::EzsignbulksendListElement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `EzmaxApi::EzsignbulksendListElement`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pki_ezsignbulksend_id')
        self.pki_ezsignbulksend_id = attributes[:'pki_ezsignbulksend_id']
      else
        self.pki_ezsignbulksend_id = nil
      end

      if attributes.key?(:'fki_ezsignfoldertype_id')
        self.fki_ezsignfoldertype_id = attributes[:'fki_ezsignfoldertype_id']
      else
        self.fki_ezsignfoldertype_id = nil
      end

      if attributes.key?(:'s_ezsignbulksend_description')
        self.s_ezsignbulksend_description = attributes[:'s_ezsignbulksend_description']
      else
        self.s_ezsignbulksend_description = nil
      end

      if attributes.key?(:'s_ezsignfoldertype_name_x')
        self.s_ezsignfoldertype_name_x = attributes[:'s_ezsignfoldertype_name_x']
      else
        self.s_ezsignfoldertype_name_x = nil
      end

      if attributes.key?(:'b_ezsignbulksend_needvalidation')
        self.b_ezsignbulksend_needvalidation = attributes[:'b_ezsignbulksend_needvalidation']
      else
        self.b_ezsignbulksend_needvalidation = nil
      end

      if attributes.key?(:'i_ezsignbulksendtransmission')
        self.i_ezsignbulksendtransmission = attributes[:'i_ezsignbulksendtransmission']
      else
        self.i_ezsignbulksendtransmission = nil
      end

      if attributes.key?(:'i_ezsignfolder')
        self.i_ezsignfolder = attributes[:'i_ezsignfolder']
      else
        self.i_ezsignfolder = nil
      end

      if attributes.key?(:'i_ezsigndocument')
        self.i_ezsigndocument = attributes[:'i_ezsigndocument']
      else
        self.i_ezsigndocument = nil
      end

      if attributes.key?(:'i_ezsignsignature')
        self.i_ezsignsignature = attributes[:'i_ezsignsignature']
      else
        self.i_ezsignsignature = nil
      end

      if attributes.key?(:'i_ezsignsignature_signed')
        self.i_ezsignsignature_signed = attributes[:'i_ezsignsignature_signed']
      else
        self.i_ezsignsignature_signed = nil
      end

      if attributes.key?(:'b_ezsignbulksend_isactive')
        self.b_ezsignbulksend_isactive = attributes[:'b_ezsignbulksend_isactive']
      else
        self.b_ezsignbulksend_isactive = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @pki_ezsignbulksend_id.nil?
        invalid_properties.push('invalid value for "pki_ezsignbulksend_id", pki_ezsignbulksend_id cannot be nil.')
      end

      if @pki_ezsignbulksend_id < 0
        invalid_properties.push('invalid value for "pki_ezsignbulksend_id", must be greater than or equal to 0.')
      end

      if @fki_ezsignfoldertype_id.nil?
        invalid_properties.push('invalid value for "fki_ezsignfoldertype_id", fki_ezsignfoldertype_id cannot be nil.')
      end

      if @fki_ezsignfoldertype_id < 0
        invalid_properties.push('invalid value for "fki_ezsignfoldertype_id", must be greater than or equal to 0.')
      end

      if @s_ezsignbulksend_description.nil?
        invalid_properties.push('invalid value for "s_ezsignbulksend_description", s_ezsignbulksend_description cannot be nil.')
      end

      if @s_ezsignfoldertype_name_x.nil?
        invalid_properties.push('invalid value for "s_ezsignfoldertype_name_x", s_ezsignfoldertype_name_x cannot be nil.')
      end

      if @b_ezsignbulksend_needvalidation.nil?
        invalid_properties.push('invalid value for "b_ezsignbulksend_needvalidation", b_ezsignbulksend_needvalidation cannot be nil.')
      end

      if @i_ezsignbulksendtransmission.nil?
        invalid_properties.push('invalid value for "i_ezsignbulksendtransmission", i_ezsignbulksendtransmission cannot be nil.')
      end

      if @i_ezsignfolder.nil?
        invalid_properties.push('invalid value for "i_ezsignfolder", i_ezsignfolder cannot be nil.')
      end

      if @i_ezsigndocument.nil?
        invalid_properties.push('invalid value for "i_ezsigndocument", i_ezsigndocument cannot be nil.')
      end

      if @i_ezsignsignature.nil?
        invalid_properties.push('invalid value for "i_ezsignsignature", i_ezsignsignature cannot be nil.')
      end

      if @i_ezsignsignature_signed.nil?
        invalid_properties.push('invalid value for "i_ezsignsignature_signed", i_ezsignsignature_signed cannot be nil.')
      end

      if @b_ezsignbulksend_isactive.nil?
        invalid_properties.push('invalid value for "b_ezsignbulksend_isactive", b_ezsignbulksend_isactive cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @pki_ezsignbulksend_id.nil?
      return false if @pki_ezsignbulksend_id < 0
      return false if @fki_ezsignfoldertype_id.nil?
      return false if @fki_ezsignfoldertype_id < 0
      return false if @s_ezsignbulksend_description.nil?
      return false if @s_ezsignfoldertype_name_x.nil?
      return false if @b_ezsignbulksend_needvalidation.nil?
      return false if @i_ezsignbulksendtransmission.nil?
      return false if @i_ezsignfolder.nil?
      return false if @i_ezsigndocument.nil?
      return false if @i_ezsignsignature.nil?
      return false if @i_ezsignsignature_signed.nil?
      return false if @b_ezsignbulksend_isactive.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] pki_ezsignbulksend_id Value to be assigned
    def pki_ezsignbulksend_id=(pki_ezsignbulksend_id)
      if pki_ezsignbulksend_id.nil?
        fail ArgumentError, 'pki_ezsignbulksend_id cannot be nil'
      end

      if pki_ezsignbulksend_id < 0
        fail ArgumentError, 'invalid value for "pki_ezsignbulksend_id", must be greater than or equal to 0.'
      end

      @pki_ezsignbulksend_id = pki_ezsignbulksend_id
    end

    # Custom attribute writer method with validation
    # @param [Object] fki_ezsignfoldertype_id Value to be assigned
    def fki_ezsignfoldertype_id=(fki_ezsignfoldertype_id)
      if fki_ezsignfoldertype_id.nil?
        fail ArgumentError, 'fki_ezsignfoldertype_id cannot be nil'
      end

      if fki_ezsignfoldertype_id < 0
        fail ArgumentError, 'invalid value for "fki_ezsignfoldertype_id", must be greater than or equal to 0.'
      end

      @fki_ezsignfoldertype_id = fki_ezsignfoldertype_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pki_ezsignbulksend_id == o.pki_ezsignbulksend_id &&
          fki_ezsignfoldertype_id == o.fki_ezsignfoldertype_id &&
          s_ezsignbulksend_description == o.s_ezsignbulksend_description &&
          s_ezsignfoldertype_name_x == o.s_ezsignfoldertype_name_x &&
          b_ezsignbulksend_needvalidation == o.b_ezsignbulksend_needvalidation &&
          i_ezsignbulksendtransmission == o.i_ezsignbulksendtransmission &&
          i_ezsignfolder == o.i_ezsignfolder &&
          i_ezsigndocument == o.i_ezsigndocument &&
          i_ezsignsignature == o.i_ezsignsignature &&
          i_ezsignsignature_signed == o.i_ezsignsignature_signed &&
          b_ezsignbulksend_isactive == o.b_ezsignbulksend_isactive
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pki_ezsignbulksend_id, fki_ezsignfoldertype_id, s_ezsignbulksend_description, s_ezsignfoldertype_name_x, b_ezsignbulksend_needvalidation, i_ezsignbulksendtransmission, i_ezsignfolder, i_ezsigndocument, i_ezsignsignature, i_ezsignsignature_signed, b_ezsignbulksend_isactive].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = EzmaxApi.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
