=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module EzmaxApi
  # Request for POST /2/object/ezsignfolder/{pkiEzsignfolderID}/importEzsigntemplatepackage
  class EzsignfolderImportEzsigntemplatepackageV2Request < ApiModelBase
    # The unique ID of the Ezsigntemplatepackage
    attr_accessor :fki_ezsigntemplatepackage_id

    # The maximum date and time at which the Ezsigndocument can be signed.
    attr_accessor :dt_ezsigndocument_duedate

    attr_accessor :a_obj_import_ezsigntemplatepackage_relation

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'fki_ezsigntemplatepackage_id' => :'fkiEzsigntemplatepackageID',
        :'dt_ezsigndocument_duedate' => :'dtEzsigndocumentDuedate',
        :'a_obj_import_ezsigntemplatepackage_relation' => :'a_objImportEzsigntemplatepackageRelation'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'fki_ezsigntemplatepackage_id' => :'Integer',
        :'dt_ezsigndocument_duedate' => :'String',
        :'a_obj_import_ezsigntemplatepackage_relation' => :'Array<CustomImportEzsigntemplatepackageRelationRequest>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `EzmaxApi::EzsignfolderImportEzsigntemplatepackageV2Request` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `EzmaxApi::EzsignfolderImportEzsigntemplatepackageV2Request`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'fki_ezsigntemplatepackage_id')
        self.fki_ezsigntemplatepackage_id = attributes[:'fki_ezsigntemplatepackage_id']
      else
        self.fki_ezsigntemplatepackage_id = nil
      end

      if attributes.key?(:'dt_ezsigndocument_duedate')
        self.dt_ezsigndocument_duedate = attributes[:'dt_ezsigndocument_duedate']
      else
        self.dt_ezsigndocument_duedate = nil
      end

      if attributes.key?(:'a_obj_import_ezsigntemplatepackage_relation')
        if (value = attributes[:'a_obj_import_ezsigntemplatepackage_relation']).is_a?(Array)
          self.a_obj_import_ezsigntemplatepackage_relation = value
        end
      else
        self.a_obj_import_ezsigntemplatepackage_relation = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @fki_ezsigntemplatepackage_id.nil?
        invalid_properties.push('invalid value for "fki_ezsigntemplatepackage_id", fki_ezsigntemplatepackage_id cannot be nil.')
      end

      if @fki_ezsigntemplatepackage_id < 0
        invalid_properties.push('invalid value for "fki_ezsigntemplatepackage_id", must be greater than or equal to 0.')
      end

      if @dt_ezsigndocument_duedate.nil?
        invalid_properties.push('invalid value for "dt_ezsigndocument_duedate", dt_ezsigndocument_duedate cannot be nil.')
      end

      if @a_obj_import_ezsigntemplatepackage_relation.nil?
        invalid_properties.push('invalid value for "a_obj_import_ezsigntemplatepackage_relation", a_obj_import_ezsigntemplatepackage_relation cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @fki_ezsigntemplatepackage_id.nil?
      return false if @fki_ezsigntemplatepackage_id < 0
      return false if @dt_ezsigndocument_duedate.nil?
      return false if @a_obj_import_ezsigntemplatepackage_relation.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] fki_ezsigntemplatepackage_id Value to be assigned
    def fki_ezsigntemplatepackage_id=(fki_ezsigntemplatepackage_id)
      if fki_ezsigntemplatepackage_id.nil?
        fail ArgumentError, 'fki_ezsigntemplatepackage_id cannot be nil'
      end

      if fki_ezsigntemplatepackage_id < 0
        fail ArgumentError, 'invalid value for "fki_ezsigntemplatepackage_id", must be greater than or equal to 0.'
      end

      @fki_ezsigntemplatepackage_id = fki_ezsigntemplatepackage_id
    end

    # Custom attribute writer method with validation
    # @param [Object] dt_ezsigndocument_duedate Value to be assigned
    def dt_ezsigndocument_duedate=(dt_ezsigndocument_duedate)
      if dt_ezsigndocument_duedate.nil?
        fail ArgumentError, 'dt_ezsigndocument_duedate cannot be nil'
      end

      @dt_ezsigndocument_duedate = dt_ezsigndocument_duedate
    end

    # Custom attribute writer method with validation
    # @param [Object] a_obj_import_ezsigntemplatepackage_relation Value to be assigned
    def a_obj_import_ezsigntemplatepackage_relation=(a_obj_import_ezsigntemplatepackage_relation)
      if a_obj_import_ezsigntemplatepackage_relation.nil?
        fail ArgumentError, 'a_obj_import_ezsigntemplatepackage_relation cannot be nil'
      end

      @a_obj_import_ezsigntemplatepackage_relation = a_obj_import_ezsigntemplatepackage_relation
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          fki_ezsigntemplatepackage_id == o.fki_ezsigntemplatepackage_id &&
          dt_ezsigndocument_duedate == o.dt_ezsigndocument_duedate &&
          a_obj_import_ezsigntemplatepackage_relation == o.a_obj_import_ezsigntemplatepackage_relation
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [fki_ezsigntemplatepackage_id, dt_ezsigndocument_duedate, a_obj_import_ezsigntemplatepackage_relation].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
