=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module EzmaxApi
  # 
  class EzsignfolderDuplicateV1Request < ApiModelBase
    # The description of the Ezsignfolder
    attr_accessor :s_ezsignfolder_description

    attr_accessor :a_fki_ezsignfoldersignerassociation_id

    attr_accessor :a_obj_ezsigndocument

    # Note about the Ezsignfolder
    attr_accessor :t_ezsignfolder_note

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'s_ezsignfolder_description' => :'sEzsignfolderDescription',
        :'a_fki_ezsignfoldersignerassociation_id' => :'a_fkiEzsignfoldersignerassociationID',
        :'a_obj_ezsigndocument' => :'a_objEzsigndocument',
        :'t_ezsignfolder_note' => :'tEzsignfolderNote'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'s_ezsignfolder_description' => :'String',
        :'a_fki_ezsignfoldersignerassociation_id' => :'Array<Integer>',
        :'a_obj_ezsigndocument' => :'Array<CustomEzsigndocumentDuplicateRequest>',
        :'t_ezsignfolder_note' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `EzmaxApi::EzsignfolderDuplicateV1Request` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `EzmaxApi::EzsignfolderDuplicateV1Request`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'s_ezsignfolder_description')
        self.s_ezsignfolder_description = attributes[:'s_ezsignfolder_description']
      else
        self.s_ezsignfolder_description = nil
      end

      if attributes.key?(:'a_fki_ezsignfoldersignerassociation_id')
        if (value = attributes[:'a_fki_ezsignfoldersignerassociation_id']).is_a?(Array)
          self.a_fki_ezsignfoldersignerassociation_id = value
        end
      else
        self.a_fki_ezsignfoldersignerassociation_id = nil
      end

      if attributes.key?(:'a_obj_ezsigndocument')
        if (value = attributes[:'a_obj_ezsigndocument']).is_a?(Array)
          self.a_obj_ezsigndocument = value
        end
      else
        self.a_obj_ezsigndocument = nil
      end

      if attributes.key?(:'t_ezsignfolder_note')
        self.t_ezsignfolder_note = attributes[:'t_ezsignfolder_note']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @s_ezsignfolder_description.nil?
        invalid_properties.push('invalid value for "s_ezsignfolder_description", s_ezsignfolder_description cannot be nil.')
      end

      pattern = Regexp.new(/^.{0,75}$/)
      if @s_ezsignfolder_description !~ pattern
        invalid_properties.push("invalid value for \"s_ezsignfolder_description\", must conform to the pattern #{pattern}.")
      end

      if @a_fki_ezsignfoldersignerassociation_id.nil?
        invalid_properties.push('invalid value for "a_fki_ezsignfoldersignerassociation_id", a_fki_ezsignfoldersignerassociation_id cannot be nil.')
      end

      if @a_obj_ezsigndocument.nil?
        invalid_properties.push('invalid value for "a_obj_ezsigndocument", a_obj_ezsigndocument cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @s_ezsignfolder_description.nil?
      return false if @s_ezsignfolder_description !~ Regexp.new(/^.{0,75}$/)
      return false if @a_fki_ezsignfoldersignerassociation_id.nil?
      return false if @a_obj_ezsigndocument.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] s_ezsignfolder_description Value to be assigned
    def s_ezsignfolder_description=(s_ezsignfolder_description)
      if s_ezsignfolder_description.nil?
        fail ArgumentError, 's_ezsignfolder_description cannot be nil'
      end

      pattern = Regexp.new(/^.{0,75}$/)
      if s_ezsignfolder_description !~ pattern
        fail ArgumentError, "invalid value for \"s_ezsignfolder_description\", must conform to the pattern #{pattern}."
      end

      @s_ezsignfolder_description = s_ezsignfolder_description
    end

    # Custom attribute writer method with validation
    # @param [Object] a_fki_ezsignfoldersignerassociation_id Value to be assigned
    def a_fki_ezsignfoldersignerassociation_id=(a_fki_ezsignfoldersignerassociation_id)
      if a_fki_ezsignfoldersignerassociation_id.nil?
        fail ArgumentError, 'a_fki_ezsignfoldersignerassociation_id cannot be nil'
      end

      @a_fki_ezsignfoldersignerassociation_id = a_fki_ezsignfoldersignerassociation_id
    end

    # Custom attribute writer method with validation
    # @param [Object] a_obj_ezsigndocument Value to be assigned
    def a_obj_ezsigndocument=(a_obj_ezsigndocument)
      if a_obj_ezsigndocument.nil?
        fail ArgumentError, 'a_obj_ezsigndocument cannot be nil'
      end

      @a_obj_ezsigndocument = a_obj_ezsigndocument
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          s_ezsignfolder_description == o.s_ezsignfolder_description &&
          a_fki_ezsignfoldersignerassociation_id == o.a_fki_ezsignfoldersignerassociation_id &&
          a_obj_ezsigndocument == o.a_obj_ezsigndocument &&
          t_ezsignfolder_note == o.t_ezsignfolder_note
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [s_ezsignfolder_description, a_fki_ezsignfoldersignerassociation_id, a_obj_ezsigndocument, t_ezsignfolder_note].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
