=begin
#eZmax API Definition (Full)

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module EzmaxApi
  # A Infrastructureregion AutocompleteElement Response
  class InfrastructureregionAutocompleteElementResponse < ApiModelBase
    # The unique ID of the Infrastructureregion
    attr_accessor :pki_infrastructureregion_id

    # The region code
    attr_accessor :s_infrastructureregion_code

    # Whether Infrastructureregion is Programmer or not
    attr_accessor :b_infrastructureregion_programmer

    # Whether the Infrastructureregion is active or not
    attr_accessor :b_infrastructureregion_isactive

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pki_infrastructureregion_id' => :'pkiInfrastructureregionID',
        :'s_infrastructureregion_code' => :'sInfrastructureregionCode',
        :'b_infrastructureregion_programmer' => :'bInfrastructureregionProgrammer',
        :'b_infrastructureregion_isactive' => :'bInfrastructureregionIsactive'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pki_infrastructureregion_id' => :'Integer',
        :'s_infrastructureregion_code' => :'String',
        :'b_infrastructureregion_programmer' => :'Boolean',
        :'b_infrastructureregion_isactive' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `EzmaxApi::InfrastructureregionAutocompleteElementResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `EzmaxApi::InfrastructureregionAutocompleteElementResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pki_infrastructureregion_id')
        self.pki_infrastructureregion_id = attributes[:'pki_infrastructureregion_id']
      else
        self.pki_infrastructureregion_id = nil
      end

      if attributes.key?(:'s_infrastructureregion_code')
        self.s_infrastructureregion_code = attributes[:'s_infrastructureregion_code']
      else
        self.s_infrastructureregion_code = nil
      end

      if attributes.key?(:'b_infrastructureregion_programmer')
        self.b_infrastructureregion_programmer = attributes[:'b_infrastructureregion_programmer']
      else
        self.b_infrastructureregion_programmer = nil
      end

      if attributes.key?(:'b_infrastructureregion_isactive')
        self.b_infrastructureregion_isactive = attributes[:'b_infrastructureregion_isactive']
      else
        self.b_infrastructureregion_isactive = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @pki_infrastructureregion_id.nil?
        invalid_properties.push('invalid value for "pki_infrastructureregion_id", pki_infrastructureregion_id cannot be nil.')
      end

      if @pki_infrastructureregion_id > 255
        invalid_properties.push('invalid value for "pki_infrastructureregion_id", must be smaller than or equal to 255.')
      end

      if @pki_infrastructureregion_id < 1
        invalid_properties.push('invalid value for "pki_infrastructureregion_id", must be greater than or equal to 1.')
      end

      if @s_infrastructureregion_code.nil?
        invalid_properties.push('invalid value for "s_infrastructureregion_code", s_infrastructureregion_code cannot be nil.')
      end

      if @b_infrastructureregion_programmer.nil?
        invalid_properties.push('invalid value for "b_infrastructureregion_programmer", b_infrastructureregion_programmer cannot be nil.')
      end

      if @b_infrastructureregion_isactive.nil?
        invalid_properties.push('invalid value for "b_infrastructureregion_isactive", b_infrastructureregion_isactive cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @pki_infrastructureregion_id.nil?
      return false if @pki_infrastructureregion_id > 255
      return false if @pki_infrastructureregion_id < 1
      return false if @s_infrastructureregion_code.nil?
      return false if @b_infrastructureregion_programmer.nil?
      return false if @b_infrastructureregion_isactive.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] pki_infrastructureregion_id Value to be assigned
    def pki_infrastructureregion_id=(pki_infrastructureregion_id)
      if pki_infrastructureregion_id.nil?
        fail ArgumentError, 'pki_infrastructureregion_id cannot be nil'
      end

      if pki_infrastructureregion_id > 255
        fail ArgumentError, 'invalid value for "pki_infrastructureregion_id", must be smaller than or equal to 255.'
      end

      if pki_infrastructureregion_id < 1
        fail ArgumentError, 'invalid value for "pki_infrastructureregion_id", must be greater than or equal to 1.'
      end

      @pki_infrastructureregion_id = pki_infrastructureregion_id
    end

    # Custom attribute writer method with validation
    # @param [Object] s_infrastructureregion_code Value to be assigned
    def s_infrastructureregion_code=(s_infrastructureregion_code)
      if s_infrastructureregion_code.nil?
        fail ArgumentError, 's_infrastructureregion_code cannot be nil'
      end

      @s_infrastructureregion_code = s_infrastructureregion_code
    end

    # Custom attribute writer method with validation
    # @param [Object] b_infrastructureregion_programmer Value to be assigned
    def b_infrastructureregion_programmer=(b_infrastructureregion_programmer)
      if b_infrastructureregion_programmer.nil?
        fail ArgumentError, 'b_infrastructureregion_programmer cannot be nil'
      end

      @b_infrastructureregion_programmer = b_infrastructureregion_programmer
    end

    # Custom attribute writer method with validation
    # @param [Object] b_infrastructureregion_isactive Value to be assigned
    def b_infrastructureregion_isactive=(b_infrastructureregion_isactive)
      if b_infrastructureregion_isactive.nil?
        fail ArgumentError, 'b_infrastructureregion_isactive cannot be nil'
      end

      @b_infrastructureregion_isactive = b_infrastructureregion_isactive
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pki_infrastructureregion_id == o.pki_infrastructureregion_id &&
          s_infrastructureregion_code == o.s_infrastructureregion_code &&
          b_infrastructureregion_programmer == o.b_infrastructureregion_programmer &&
          b_infrastructureregion_isactive == o.b_infrastructureregion_isactive
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pki_infrastructureregion_id, s_infrastructureregion_code, b_infrastructureregion_programmer, b_infrastructureregion_isactive].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
