=begin
#eZmax API Definition

#This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.2
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1-SNAPSHOT

=end

require 'date'
require 'time'

module EzmaxApi
  class FieldEEzsignfoldertypePrivacylevel
    USER = "User".freeze
    USERGROUP = "Usergroup".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = FieldEEzsignfoldertypePrivacylevel.constants.select { |c| FieldEEzsignfoldertypePrivacylevel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #FieldEEzsignfoldertypePrivacylevel" if constantValues.empty?
      value
    end
  end
end
